### ISSUE TITLE
Merge S3 prefetch and range read functionality?

### ISSUE THREAD

**Issue by dblacknc** [kisscelia/cosbench-ehualu#2]
There's another fork of COSbench adding object prefetch and more importantly to me, range reads.   The implementation of the latter is limited in that for each workstage the size of the range is fixed and offset into the object is random.  That's good enough for me, for now.

Would you please add this functionality - or something like it, to your fork, from this one?
https://github.com/bissenbay/cosbench

I very much appreciate all the improvements you've made.  Great to finally see v4 signatures (default) with the s3v2 driver, multi-part uploads, and a simple way to disable SSL cert checking!

**Comment by kisscelia** [comment]
Hi, @dblacknc 

I am sorry to tell you that i don't know how to use prefetch and range read.

Can you submit a PR?

**Comment by dblacknc** [comment]
I haven't done a PR before, and will look into doing this.  It is a patch to the S3 plugin.

**Comment by bissenbay** [comment]
Hi @dblacknc , @kisscelia thanks for reaching me out, yes, I'm more than happy to open a PR.

**Comment by kisscelia** [comment]
Hi @dblacknc @bissenbay 

Thank you all.

My local storage is ceph too, and i will learn how to use the prefetch and range read, thanks.
