### ISSUE TITLE
s() and r() iterators in normal stage are broken

### ISSUE THREAD

**Issue by dblacknc** [kisscelia/cosbench-ehualu#4]
References:
https://github.com/intel-cloud/cosbench/issues/148
https://github.com/intel-cloud/cosbench/issues/31
https://github.com/intel-cloud/cosbench/issues/64

There's serious brokenness in the sequential and range iterators, when used in a "normal" workstage.
I've been testing the new mwrite mode, intending to use that to create new multipart objects rather than the r() iterator and the "prepare" stage (which doesn't at least currently support multipart).

s() is said to be thread-safe.  However, I can't get that working much at all.  It seems to ignore the division strategy (other than "none") for one.   The r() selector sort of works, yet only with worker counts relatively low, below 10 or so.  Above, that some objects are overwritten when they shouldn't and others not created at all - guessing because of race conditions.  The "object" division strategy must be used unless the worker count is >= containers (then the "container" strategy is ok) - not itself a bug.

The original developers of COSbench appear to have tested primarily using the u() random iterator - and that does work for the purpose, yet there are times when I want to ensure a certain set of objects are written or deleted, within a normal workstage.

Just getting this original issue out there, since it sure could use some help.  I'll next have a look at the code myself to see what might be happening, then add a comment here if I figure it out.  One of the original developers says this in issue #64 and did a commit, though that didn't seem to fix it.   I believe it was just not really fixed before development stopped at 0.4.2:  "using atomic structure in Range selector is insufficient to avoid race condition, synchronization primitive will be added in object picker to coordinate container and object generators."

**Comment by kisscelia** [comment]
Hi, @dblacknc :
Can you share your xml file?

BTW, it's a good idea to add mwrite in prepare stage, i will try it, thanks.

**Comment by dblacknc** [comment]
Here's an example XML workstage that shows a problem:

`    <workstage name="create-objects">
      <work name="main" division="object" type="normal" workers="10" totalOps="1000">
        <operation type="mwrite" config="cprefix=dc; containers=c(1); objects=s(1,1000); sizes=c(100)MiB; createContainer=true"/>
      </work>
        </workstage>
`

The 10 workers all write the same myobjects1-myobjects100 to bucket dc1 then stop, after reaching total 1000 operations.  What should happen is the work is divided among them, e.g. objects 1-100 to worker 1, objects 101-200 to worker 2 and so forth.   Here it's as if division directive just isn't working for the s() iterator.   This *does* work with s(1,1000), except there are apparent race conditions that appear with even only 10 workers.

I considered adding an "mprepare" method or simply making the chunking=true directive in the prepare stage use doMWrite instead of doWrite.   Better to fix the s() iterator though, as it'd be very useful.

**Comment by kisscelia** [comment]
Hi, 
1st, mwrite is the same logic to the write operation.
2nd, as i know, s() is seq, and object selected only once.
3rd, about division, here is a snapshot as below:
![image](https://user-images.githubusercontent.com/13063673/147304525-86fe0c38-6952-4d51-9135-ec759fc15f84.png)

4th, mprepare is a good idea, i will try to do it, when i have time, thanks.

**Comment by kisscelia** [comment]
Hi, @dblacknc :
mprepare is ok, pls have a try, thanks.
